# Generated by Django 5.2 on 2025-04-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_posts_options_alter_posts_caption_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
