# Generated by Django 5.2 on 2025-04-18 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_posts_id_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='n_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f560d2e-abb0-433e-9a7c-5c9ee2af2d50'), primary_key=True, serialize=False),
        ),
    ]
